name: Run Selenium Pytest 
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        suite:
          - tests/test_login.py
          - tests/test_api.py
    steps:
      - name: Checkout source code from github
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.13'

      - name: Install necessary libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome library
        uses: browser-actions/setup-chrome@v1

      - name: Create a test report Folder
        run: mkdir -p report

      # - name: Run Test 
      #   #run: pytest -m "smoke or api" --html=report/report.html --self-contained-html
     

      - name: Run Test
        run: 
          pytest ${{ matrix.suite }} --html=report/report.html --self-contained-html

      - name: Upload file report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report-${{ matrix.suite }}
          path: report/report.html